/**
 * Error Codes
 * Consistent error handling across the application
 */

export enum ErrorCode {
  // Authentication
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',

  // Resource
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',

  // Task
  TASK_BLOCKED = 'TASK_BLOCKED',
  TASK_MISSING_ASSIGNEES = 'TASK_MISSING_ASSIGNEES',
  TASK_MISSING_PLANNED_DATE = 'TASK_MISSING_PLANNED_DATE',
  TASK_REQUIRES_INSPECTION = 'TASK_REQUIRES_INSPECTION',

  // Inspection
  INSPECTION_INCOMPLETE_CHECKLIST = 'INSPECTION_INCOMPLETE_CHECKLIST',
  INSPECTION_MISSING_REQUIRED_PHOTO = 'INSPECTION_MISSING_REQUIRED_PHOTO',

  // Issue
  ISSUE_INVALID_STATUS_TRANSITION = 'ISSUE_INVALID_STATUS_TRANSITION',

  // Delivery
  DELIVERY_BLOCKS_WORK = 'DELIVERY_BLOCKS_WORK',

  // Decision
  DECISION_BLOCKS_WORK = 'DECISION_BLOCKS_WORK',
  DECISION_ALREADY_DECIDED = 'DECISION_ALREADY_DECIDED',

  // Server
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    public message: string,
    public statusCode: number = 500,
    public details?: Record<string, any>
  ) {
    super(message);
    this.name = 'AppError';
  }
}
